/*
 * The 46656 single-digit templates: every valid full placement of one digit
 * (9 cells, one per row, all columns and boxes distinct). HoDoKu ships these in
 * templates.dat; here they are regenerated by backtracking at first use (fast in
 * Node) and cached, avoiding a binary asset.
 */

import { CellSet } from "./cell-set.js";

let cache: CellSet[] | null = null;

/** Returns all 46656 single-digit placement templates (lazily generated). */
export function getSingleDigitTemplates(): CellSet[] {
  if (cache) return cache;
  const out: CellSet[] = [];
  const cols = new Int8Array(9); // chosen column per row
  const rec = (row: number, usedCols: number, usedBoxes: number): void => {
    if (row === 9) {
      const s = new CellSet();
      for (let r = 0; r < 9; r++) s.add(r * 9 + cols[r]!);
      out.push(s);
      return;
    }
    const boxBase = ((row / 3) | 0) * 3;
    for (let c = 0; c < 9; c++) {
      const colBit = 1 << c;
      if (usedCols & colBit) continue;
      const boxBit = 1 << (boxBase + ((c / 3) | 0));
      if (usedBoxes & boxBit) continue;
      cols[row] = c;
      rec(row + 1, usedCols | colBit, usedBoxes | boxBit);
    }
  };
  rec(0, 0, 0);
  cache = out;
  return out;
}
